runtime: php
env: flex

runtime_config: 
  document_root: ./src/public

# Ensure we skip ".env", which is only for local development
skip_files: 
    - .env

env_variables:
    APP_NAME: NukeStore
    APP_ENV: production
    APP_DEBUG: false
    DB_CONNECTION: mysql
    DB_DATABASE: $DB_DATABASE 
    DB_USERNAME: $DB_USERNAME 
    DB_PORT: $DB_PORT
    DB_HOST: $DB_HOST
    APP_KEY: $APP_KEY
    DB_PASSWORD: $DB_PASSWORD

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 20
