name: deploy laravel

on:
  push:
    branches: [andres/deploy]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env: 
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SOCKET: "cloudsql"
      APP_NAME: "NukeStore"
      APP_ENV: "local"
      APP_KEY: ${{ secrets.APP_KEY }}
      APP_DEBUG: true
      DB_CONNECTION: "mysql"

    steps:
      - uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "set up google cloud sdk"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "install google cloud sql auth proxy"
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy &&
          chmod +x cloud_sql_proxy

      - name: "install dependencies"
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          version: 2.x
          working_dir: ./src

      # - name: "run migrations"
      #   run: ./cloud_sql_proxy -instances=${{ secrets.GCP_PROJECT_ID }}:${{ secrets.GCP_REGION }}:${{ secrets.GCP_DB_INSTANCE }}=tcp:${{ secrets.DB_PORT }} & php ./src/artisan migrate

      - name: "deploy to gae"
        uses: google-github-actions/deploy-appengine@v1
        with:
          project_id: "${{ secrets.GCP_PROJECT_ID }}"
          working_directory: .
          env_vars: |-
            APP_NAME=NukeStore
            APP_ENV=production
            APP_DEBUG=false
            DB_CONNECTION=mysql
            APP_KEY="${{ secrets.APP_KEY }}"
            DB_HOST="${{ secrets.DB_HOST }}"
            DB_PORT="${{ secrets.DB_PORT }}"
            DB_DATABASE="${{ secrets.DB_DATABASE }}"
            DB_USERNAME="${{ secrets.DB_USERNAME }}"
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
